<?php require_once 'UsuariosController.php'; ?>
<?php include("includes/a_config.php"); ?>
<!DOCTYPE html>
<html lang="es">

<head>
    <?php include("includes/head-tag-contents.php"); ?>
</head>

<body>

    <?php include("includes/navigation.php"); ?>
    <main>

        <section class="page-section terminosLegales" id="terminosLegales">
            <div class="container-fluid my-5">
            <header class="text-center">
<h2 class="m-auto">POL&Iacute;TICA DE PRIVACIDAD DEL SITIO WEB</h2>
<h4><span class="blanc-space ng-binding">www.lucecine.com</span></h4>
</header>
<div>
<h3>I. POL&Iacute;TICA DE PRIVACIDAD Y PROTECCI&Oacute;N DE DATOS</h3>
<p>Respetando lo establecido en la legislaci&oacute;n vigente,&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;(en adelante, tambi&eacute;n Sitio Web) se compromete a adoptar las medidas t&eacute;cnicas y organizativas necesarias, seg&uacute;n el nivel de seguridad adecuado al riesgo de los datos recogidos.</p>
<h4>Leyes que incorpora esta pol&iacute;tica de privacidad</h4>
<p>Esta pol&iacute;tica de privacidad est&aacute; adaptada a la normativa espa&ntilde;ola y europea vigente en materia de protecci&oacute;n de datos personales en internet. En concreto, la misma respeta las siguientes normas:</p>
<ul>
<li>El Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales y a la libre circulaci&oacute;n de estos datos (RGPD).</li>
<li>La Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales (LOPD-GDD).</li>
<li>El Real Decreto 1720/2007, de 21 de diciembre, por el que se aprueba el Reglamento de desarrollo de la Ley Org&aacute;nica 15/1999, de 13 de diciembre, de Protecci&oacute;n de Datos de Car&aacute;cter Personal (RDLOPD).</li>
<li>La Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Informaci&oacute;n y de Comercio Electr&oacute;nico (LSSI-CE).</li>
</ul>
<h4>Identidad del responsable del tratamiento de los datos personales</h4>
<p class="">El responsable del tratamiento de los datos personales recogidos en&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;es:&nbsp;<span class="blanc-space ng-binding">Lucecine S.L.</span>, provista de NIF/CIF:&nbsp;<span class="blanc-space ng-binding">A-80080000</span>&nbsp;e inscrito en:&nbsp;<span class="blanc-space ng-binding">Registro Mercantil de C&oacute;rdoba</span>&nbsp;con los siguientes datos registrales:&nbsp;<span class="blanc-space ng-binding">Tomo 0, P&aacute;gina 9, Hoja 888</span>, cuyo representante es:&nbsp;<span class="blanc-space ng-binding">Izan Herenas Guerrero</span>&nbsp;(en adelante, Responsable del tratamiento). Sus datos de contacto son los siguientes:</p>
<p>Direcci&oacute;n:&nbsp;<span class="blanc-space ng-binding">C/ Torremolinos, N&ordm; 13, 28821 - Coslada (Madrid</span></p>
<p>Tel&eacute;fono de contacto:&nbsp;<span class="blanc-space ng-binding">961111111</span></p>
<p class="" style="box-sizing: border-box; font-family: Roboto, sans-serif; margin-top: 0px; margin-bottom: 1rem; line-height: 1.7rem;">Fax:&nbsp;<span class="blanc-space ng-binding">968856000</span></p>
<p>Email de contacto:&nbsp;<span class="blanc-space ng-binding">lucecine@gmail.com</span></p>
<h4>Registro de Datos de Car&aacute;cter Personal</h4>
<p>En cumplimiento de lo establecido en el RGPD y la LOPD-GDD, le informamos que los datos personales recabados por&nbsp;<span class="blanc-space ng-binding">Lucecine</span>, mediante los formularios extendidos en sus p&aacute;ginas quedar&aacute;n incorporados y ser&aacute;n tratados en nuestro fichero con el fin de poder facilitar, agilizar y cumplir los compromisos establecidos entre&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;y el Usuario o el mantenimiento de la relaci&oacute;n que se establezca en los formularios que este rellene, o para atender una solicitud o consulta del mismo. Asimismo, de conformidad con lo previsto en el RGPD y la LOPD-GDD, salvo que sea de aplicaci&oacute;n la excepci&oacute;n prevista en el art&iacute;culo 30.5 del RGPD, se mantiene un registro de actividades de tratamiento que especifica, seg&uacute;n sus finalidades, las actividades de tratamiento llevadas a cabo y las dem&aacute;s circunstancias establecidas en el RGPD.</p>
<h4>Principios aplicables al tratamiento de los datos personales</h4>
<p>El tratamiento de los datos personales del Usuario se someter&aacute; a los siguientes principios recogidos en el art&iacute;culo 5 del RGPD y en el art&iacute;culo 4 y siguientes de la Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales:</p>
<ul>
<li>Principio de licitud, lealtad y transparencia: se requerir&aacute; en todo momento el consentimiento del Usuario previa informaci&oacute;n completamente transparente de los fines para los cuales se recogen los datos personales.</li>
<li>Principio de limitaci&oacute;n de la finalidad: los datos personales ser&aacute;n recogidos con fines determinados, expl&iacute;citos y leg&iacute;timos.</li>
<li>Principio de minimizaci&oacute;n de datos: los datos personales recogidos ser&aacute;n &uacute;nicamente los estrictamente necesarios en relaci&oacute;n con los fines para los que son tratados.</li>
<li>Principio de exactitud: los datos personales deben ser exactos y estar siempre actualizados.</li>
<li>Principio de limitaci&oacute;n del plazo de conservaci&oacute;n: los datos personales solo ser&aacute;n mantenidos de forma que se permita la identificaci&oacute;n del Usuario durante el tiempo necesario para los fines de su tratamiento.</li>
<li>Principio de integridad y confidencialidad: los datos personales ser&aacute;n tratados de manera que se garantice su seguridad y confidencialidad.</li>
<li>Principio de responsabilidad proactiva: el Responsable del tratamiento ser&aacute; responsable de asegurar que los principios anteriores se cumplen.</li>
</ul>
<h4>Categor&iacute;as de datos personales</h4>
<p>Las categor&iacute;as de datos que se tratan en&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;son &uacute;nicamente datos identificativos. En ning&uacute;n caso, se tratan categor&iacute;as especiales de datos personales en el sentido del art&iacute;culo 9 del RGPD.</p>
<h4>Base legal para el tratamiento de los datos personales</h4>
<p>La base legal para el tratamiento de los datos personales es el consentimiento.&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;se compromete a recabar el consentimiento expreso y verificable del Usuario para el tratamiento de sus datos personales para uno o varios fines espec&iacute;ficos.</p>
<p>El Usuario tendr&aacute; derecho a retirar su consentimiento en cualquier momento. Ser&aacute; tan f&aacute;cil retirar el consentimiento como darlo. Como regla general, la retirada del consentimiento no condicionar&aacute; el uso del Sitio Web.</p>
<p>En las ocasiones en las que el Usuario deba o pueda facilitar sus datos a trav&eacute;s de formularios para realizar consultas, solicitar informaci&oacute;n o por motivos relacionados con el contenido del Sitio Web, se le informar&aacute; en caso de que la cumplimentaci&oacute;n de alguno de ellos sea obligatoria debido a que los mismos sean imprescindibles para el correcto desarrollo de la operaci&oacute;n realizada.</p>
<h4>Fines del tratamiento a que se destinan los datos personales</h4>
<p>Los datos personales son recabados y gestionados por&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;con la finalidad de poder facilitar, agilizar y cumplir los compromisos establecidos entre el Sitio Web y el Usuario o el mantenimiento de la relaci&oacute;n que se establezca en los formularios que este &uacute;ltimo rellene o para atender una solicitud o consulta.</p>
<p>Igualmente, los datos podr&aacute;n ser utilizados con una finalidad comercial de personalizaci&oacute;n, operativa y estad&iacute;stica, y actividades propias del objeto social de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>, as&iacute; como para la extracci&oacute;n, almacenamiento de datos y estudios de marketing para adecuar el Contenido ofertado al Usuario, as&iacute; como mejorar la calidad, funcionamiento y navegaci&oacute;n por el Sitio Web.</p>
<p>En el momento en que se obtengan los datos personales, se informar&aacute; al Usuario acerca del fin o fines espec&iacute;ficos del tratamiento a que se destinar&aacute;n los datos personales; es decir, del uso o usos que se dar&aacute; a la informaci&oacute;n recopilada.</p>
<h4>Per&iacute;odos de retenci&oacute;n de los datos personales</h4>
<p>Los datos personales solo ser&aacute;n retenidos durante el tiempo m&iacute;nimo necesario para los fines de su tratamiento y, en todo caso, &uacute;nicamente durante el siguiente plazo:&nbsp;<span class="blanc-space ng-binding">18 meses</span>, o hasta que el Usuario solicite su supresi&oacute;n.</p>
<p>En el momento en que se obtengan los datos personales, se informar&aacute; al Usuario acerca del plazo durante el cual se conservar&aacute;n los datos personales o, cuando eso no sea posible, los criterios utilizados para determinar este plazo.</p>
<h4>Destinatarios de los datos personales</h4>
<p class="">Los datos personales del Usuario no ser&aacute;n compartidos con terceros.</p>
<p class="">En cualquier caso, en el momento en que se obtengan los datos personales, se informar&aacute; al Usuario acerca de los destinatarios o las categor&iacute;as de destinatarios de los datos personales.</p>
<h4>Datos personales de menores de edad</h4>
<p>Respetando lo establecido en los art&iacute;culos 8 del RGPD y 7 de la Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales, solo los mayores de 14 a&ntilde;os podr&aacute;n otorgar su consentimiento para el tratamiento de sus datos personales de forma l&iacute;cita por&nbsp;<span class="blanc-space ng-binding">Lucecine</span>. Si se trata de un menor de 14 a&ntilde;os, ser&aacute; necesario el consentimiento de los padres o tutores para el tratamiento, y este solo se considerar&aacute; l&iacute;cito en la medida en la que los mismos lo hayan autorizado.</p>
<h4>Secreto y seguridad de los datos personales</h4>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;se compromete a adoptar las medidas t&eacute;cnicas y organizativas necesarias, seg&uacute;n el nivel de seguridad adecuado al riesgo de los datos recogidos, de forma que se garantice la seguridad de los datos de car&aacute;cter personal y se evite la destrucci&oacute;n, p&eacute;rdida o alteraci&oacute;n accidental o il&iacute;cita de datos personales transmitidos, conservados o tratados de otra forma, o la comunicaci&oacute;n o acceso no autorizados a dichos datos.</p>
<p>Sin embargo, debido a que&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;no puede garantizar la inexpugnabilidad de internet ni la ausencia total de hackers u otros que accedan de modo fraudulento a los datos personales, el Responsable del tratamiento se compromete a comunicar al Usuario sin dilaci&oacute;n indebida cuando ocurra una violaci&oacute;n de la seguridad de los datos personales que sea probable que entra&ntilde;e un alto riesgo para los derechos y libertades de las personas f&iacute;sicas. Siguiendo lo establecido en el art&iacute;culo 4 del RGPD, se entiende por violaci&oacute;n de la seguridad de los datos personales toda violaci&oacute;n de la seguridad que ocasione la destrucci&oacute;n, p&eacute;rdida o alteraci&oacute;n accidental o il&iacute;cita de datos personales transmitidos, conservados o tratados de otra forma, o la comunicaci&oacute;n o acceso no autorizados a dichos datos.</p>
<p>Los datos personales ser&aacute;n tratados como confidenciales por el Responsable del tratamiento, quien se compromete a informar de y a garantizar por medio de una obligaci&oacute;n legal o contractual que dicha confidencialidad sea respetada por sus empleados, asociados, y toda persona a la cual le haga accesible la informaci&oacute;n.</p>
<h4>Derechos derivados del tratamiento de los datos personales</h4>
<p>El Usuario tiene sobre&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;y podr&aacute;, por tanto, ejercer frente al Responsable del tratamiento los siguientes derechos reconocidos en el RGPD y la Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales:</p>
<ul>
<li><em>Derecho de acceso:</em>&nbsp;Es el derecho del Usuario a obtener confirmaci&oacute;n de si&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;est&aacute; tratando o no sus datos personales y, en caso afirmativo, obtener informaci&oacute;n sobre sus datos concretos de car&aacute;cter personal y del tratamiento que&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;haya realizado o realice, as&iacute; como, entre otra, de la informaci&oacute;n disponible sobre el origen de dichos datos y los destinatarios de las comunicaciones realizadas o previstas de los mismos.</li>
<li><em>Derecho de rectificaci&oacute;n:</em>&nbsp;Es el derecho del Usuario a que se modifiquen sus datos personales que resulten ser inexactos o, teniendo en cuenta los fines del tratamiento, incompletos.</li>
<li><em>Derecho de supresi&oacute;n ("el derecho al olvido"):</em>&nbsp;Es el derecho del Usuario, siempre que la legislaci&oacute;n vigente no establezca lo contrario, a obtener la supresi&oacute;n de sus datos personales cuando estos ya no sean necesarios para los fines para los cuales fueron recogidos o tratados; el Usuario haya retirado su consentimiento al tratamiento y este no cuente con otra base legal; el Usuario se oponga al tratamiento y no exista otro motivo leg&iacute;timo para continuar con el mismo; los datos personales hayan sido tratados il&iacute;citamente; los datos personales deban suprimirse en cumplimiento de una obligaci&oacute;n legal; o los datos personales hayan sido obtenidos producto de una oferta directa de servicios de la sociedad de la informaci&oacute;n a un menor de 14 a&ntilde;os. Adem&aacute;s de suprimir los datos, el Responsable del tratamiento, teniendo en cuenta la tecnolog&iacute;a disponible y el coste de su aplicaci&oacute;n, deber&aacute; adoptar medidas razonables para informar a los responsables que est&eacute;n tratando los datos personales de la solicitud del interesado de supresi&oacute;n de cualquier enlace a esos datos personales.</li>
<li><em>Derecho a la limitaci&oacute;n del tratamiento:</em>&nbsp;Es el derecho del Usuario a limitar el tratamiento de sus datos personales. El Usuario tiene derecho a obtener la limitaci&oacute;n del tratamiento cuando impugne la exactitud de sus datos personales; el tratamiento sea il&iacute;cito; el Responsable del tratamiento ya no necesite los datos personales, pero el Usuario lo necesite para hacer reclamaciones; y cuando el Usuario se haya opuesto al tratamiento.</li>
<li><em>Derecho a la portabilidad de los datos:</em>&nbsp;En caso de que el tratamiento se efect&uacute;e por medios automatizados, el Usuario tendr&aacute; derecho a recibir del Responsable del tratamiento sus datos personales en un formato estructurado, de uso com&uacute;n y lectura mec&aacute;nica, y a transmitirlos a otro responsable del tratamiento. Siempre que sea t&eacute;cnicamente posible, el Responsable del tratamiento transmitir&aacute; directamente los datos a ese otro responsable.</li>
<li><em>Derecho de oposici&oacute;n:</em>&nbsp;Es el derecho del Usuario a que no se lleve a cabo el tratamiento de sus datos de car&aacute;cter personal o se cese el tratamiento de los mismos por parte de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>.</li>
<li><em>Derecho a no ser objeto de una decisi&oacute;n basada &uacute;nicamente en el tratamiento automatizado, incluida la elaboraci&oacute;n de perfiles:</em>&nbsp;Es el derecho del Usuario a no ser objeto de una decisi&oacute;n individualizada basada &uacute;nicamente en el tratamiento automatizado de sus datos personales, incluida la elaboraci&oacute;n de perfiles, existente salvo que la legislaci&oacute;n vigente establezca lo contrario.</li>
</ul>
<p>As&iacute; pues, el Usuario podr&aacute; ejercitar sus derechos mediante comunicaci&oacute;n escrita dirigida al Responsable del tratamiento con la referencia "RGPD-<span class="blanc-space ng-binding">www.lucecine.com</span>", especificando:</p>
<ul>
<li>Nombre, apellidos del Usuario y copia del DNI. En los casos en que se admita la representaci&oacute;n, ser&aacute; tambi&eacute;n necesaria la identificaci&oacute;n por el mismo medio de la persona que representa al Usuario, as&iacute; como el documento acreditativo de la representaci&oacute;n. La fotocopia del DNI podr&aacute; ser sustituida, por cualquier otro medio v&aacute;lido en derecho que acredite la identidad.</li>
<li>Petici&oacute;n con los motivos espec&iacute;ficos de la solicitud o informaci&oacute;n a la que se quiere acceder.</li>
<li>Domicilio a efecto de notificaciones.</li>
<li>Fecha y firma del solicitante.</li>
<li>Todo documento que acredite la petici&oacute;n que formula.</li>
</ul>
<p>Esta solicitud y todo otro documento adjunto podr&aacute; enviarse a la siguiente direcci&oacute;n y/o correo electr&oacute;nico:</p>
<p>Direcci&oacute;n postal:&nbsp;<span class="blanc-space ng-binding">C/ Torremolinos, N&ordm; 13, 28821 - Coslada (Madrid</span></p>
<p>Correo electr&oacute;nico:&nbsp;<span class="blanc-space ng-binding">lucecine@gmail.com</span></p>
<h4>Enlaces a sitios web de terceros</h4>
<p>El Sitio Web puede incluir hiperv&iacute;nculos o enlaces que permiten acceder a p&aacute;ginas web de terceros distintos de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>, y que por tanto no son operados por&nbsp;<span class="blanc-space ng-binding">Lucecine</span>. Los titulares de dichos sitios web dispondr&aacute;n de sus propias pol&iacute;ticas de protecci&oacute;n de datos, siendo ellos mismos, en cada caso, responsables de sus propios ficheros y de sus propias pr&aacute;cticas de privacidad.</p>
<h4>Reclamaciones ante la autoridad de control</h4>
<p>En caso de que el Usuario considere que existe un problema o infracci&oacute;n de la normativa vigente en la forma en la que se est&aacute;n tratando sus datos personales, tendr&aacute; derecho a la tutela judicial efectiva y a presentar una reclamaci&oacute;n ante una autoridad de control, en particular, en el Estado en el que tenga su residencia habitual, lugar de trabajo o lugar de la supuesta infracci&oacute;n. En el caso de Espa&ntilde;a, la autoridad de control es la Agencia Espa&ntilde;ola de Protecci&oacute;n de Datos (https://www.aepd.es/).</p>
<h3>II. ACEPTACI&Oacute;N Y CAMBIOS EN ESTA POL&Iacute;TICA DE PRIVACIDAD</h3>
<p>Es necesario que el Usuario haya le&iacute;do y est&eacute; conforme con las condiciones sobre la protecci&oacute;n de datos de car&aacute;cter personal contenidas en esta Pol&iacute;tica de Privacidad, as&iacute; como que acepte el tratamiento de sus datos personales para que el Responsable del tratamiento pueda proceder al mismo en la forma, durante los plazos y para las finalidades indicadas. El uso del Sitio Web implicar&aacute; la aceptaci&oacute;n de la Pol&iacute;tica de Privacidad del mismo.</p>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;se reserva el derecho a modificar su Pol&iacute;tica de Privacidad, de acuerdo a su propio criterio, o motivado por un cambio legislativo, jurisprudencial o doctrinal de la Agencia Espa&ntilde;ola de Protecci&oacute;n de Datos. Los cambios o actualizaciones de esta Pol&iacute;tica de Privacidad no ser&aacute;n notificados de forma expl&iacute;cita al Usuario. Se recomienda al Usuario consultar esta p&aacute;gina de forma peri&oacute;dica para estar al tanto de los &uacute;ltimos cambios o actualizaciones.</p>
<p>Esta Pol&iacute;tica de Privacidad fue actualizada para adaptarse al Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales y a la libre circulaci&oacute;n de estos datos (RGPD) y a la Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales.</p>
</div>
<header class="text-center">
<h2 class="m-auto">AVISO LEGAL Y CONDICIONES GENERALES DE USO</h2>
<h4><span class="blanc-space ng-binding">www.lucecine.com</span></h4>
</header>
<div>
<h3>I. INFORMACI&Oacute;N GENERAL</h3>
<p>En cumplimiento con el deber de informaci&oacute;n dispuesto en la Ley 34/2002 de Servicios de la Sociedad de la Informaci&oacute;n y el Comercio Electr&oacute;nico (LSSI-CE) de 11 de julio, se facilitan a continuaci&oacute;n los siguientes datos de informaci&oacute;n general de este sitio web:</p>
<p class="">La titularidad de este sitio web,&nbsp;<span class="blanc-space ng-binding">www.lucecine.com</span>, (en adelante, Sitio Web) la ostenta:&nbsp;<span class="blanc-space ng-binding">Lucecine S.L.</span>, provista de NIF:&nbsp;<span class="blanc-space ng-binding">A-80080000</span>&nbsp;e inscrita en:&nbsp;<span class="blanc-space ng-binding">Registro Mercantil de C&oacute;rdoba</span>&nbsp;con los siguientes datos registrales:&nbsp;<span class="blanc-space ng-binding">Tomo 0, Pagina 9, hoja 888</span>, cuyo representante es:&nbsp;<span class="blanc-space ng-binding">Izan Herenas Guerrero</span>, y cuyos datos de contacto son:</p>
<p>Direcci&oacute;n:&nbsp;<span class="blanc-space ng-binding">C/Torremolinos, N&ordm; 13, 28821 - Coslada (Madrid)</span></p>
<p>Tel&eacute;fono de contacto:&nbsp;<span class="blanc-space ng-binding">961111111</span></p>
<p class="" style="box-sizing: border-box; font-family: Roboto, sans-serif; margin-top: 0px; margin-bottom: 1rem; line-height: 1.7rem;">Fax:&nbsp;<span class="blanc-space ng-binding">968850000</span></p>
<p>Email de contacto:&nbsp;<span class="blanc-space ng-binding">lucecine@gmail.com</span></p>
<h3>II. T&Eacute;RMINOS Y CONDICIONES GENERALES DE USO</h3>
<h4>El objeto de las condiciones: El Sitio Web</h4>
<p>El objeto de las presentes Condiciones Generales de Uso (en adelante, Condiciones) es regular el acceso y la utilizaci&oacute;n del Sitio Web. A los efectos de las presentes Condiciones se entender&aacute; como Sitio Web: la apariencia externa de los interfaces de pantalla, tanto de forma est&aacute;tica como de forma din&aacute;mica, es decir, el &aacute;rbol de navegaci&oacute;n; y todos los elementos integrados tanto en los interfaces de pantalla como en el &aacute;rbol de navegaci&oacute;n (en adelante, Contenidos) y todos aquellos servicios o recursos en l&iacute;nea que en su caso ofrezca a los Usuarios (en adelante, Servicios).</p>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;se reserva la facultad de modificar, en cualquier momento, y sin aviso previo, la presentaci&oacute;n y configuraci&oacute;n del Sitio Web y de los Contenidos y Servicios que en &eacute;l pudieran estar incorporados. El Usuario reconoce y acepta que en cualquier momento&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;pueda interrumpir, desactivar y/o cancelar cualquiera de estos elementos que se integran en el Sitio Web o el acceso a los mismos.</p>
<p class="">Aparte del coste de conexi&oacute;n a trav&eacute;s de la red de telecomunicaciones suministrada por el proveedor de acceso, y que hubiere contratado el Usuario, algunos de los Contenidos o Servicios ofrecidos por&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;o, en su caso, terceros a trav&eacute;s del Sitio Web pueden encontrarse sujetos a la contrataci&oacute;n previa del Contenido o Servicio, en cuyo caso se especificar&aacute; de forma clara y/o se pondr&aacute; a disposici&oacute;n del Usuario las correspondientes Condiciones Generales o Particulares por las que esto se rija.</p>
<p>La utilizaci&oacute;n de alguno de los Contenidos o Servicios del Sitio Web podr&aacute; hacerse mediante la suscripci&oacute;n o registro previo del Usuario.</p>
<h4>El Usuario</h4>
<p>El acceso, la navegaci&oacute;n y uso del Sitio Web,&nbsp;as&iacute; como por los espacios habilitados para interactuar entre los Usuarios, y el Usuario y&nbsp;<span class="blanc-space ng-binding">Lucecine</span>, como los comentarios y/o espacios de blogging,&nbsp;confiere la condici&oacute;n de Usuario, por lo que se aceptan, desde que se inicia la navegaci&oacute;n por el Sitio Web, todas las Condiciones aqu&iacute; establecidas, as&iacute; como sus ulteriores modificaciones, sin perjuicio de la aplicaci&oacute;n de la correspondiente normativa legal de obligado cumplimiento seg&uacute;n el caso. Dada la relevancia de lo anterior, se recomienda al Usuario leerlas cada vez que visite el Sitio Web.</p>
<p>El Sitio Web de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;proporciona gran diversidad de informaci&oacute;n, servicios y datos. El Usuario asume su responsabilidad para realizar un uso correcto del Sitio Web. Esta responsabilidad se extender&aacute; a:</p>
<ul>
<li>Un uso de la informaci&oacute;n, Contenidos y/o Servicios y datos ofrecidos por&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;sin que sea contrario a lo dispuesto por las presentes Condiciones, la Ley, la moral o el orden p&uacute;blico, o que de cualquier otro modo puedan suponer lesi&oacute;n de los derechos de terceros o del mismo funcionamiento del Sitio Web.</li>
<li>La veracidad y licitud de las informaciones aportadas por el Usuario en los formularios extendidos por&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;para el acceso a ciertos Contenidos o Servicios ofrecidos por el Sitio Web. En todo caso, el Usuario notificar&aacute; de forma inmediata a&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;acerca de cualquier hecho que permita el uso indebido de la informaci&oacute;n registrada en dichos formularios, tales como, pero no solo, el robo, extrav&iacute;o, o el acceso no autorizado a identificadores y/o contrase&ntilde;as, con el fin de proceder a su inmediata cancelaci&oacute;n.</li>
</ul>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;se reserva el derecho de retirar todos aquellos comentarios y aportaciones que vulneren la ley, el respeto a la dignidad de la persona, que sean discriminatorios, xen&oacute;fobos, racistas, pornogr&aacute;ficos, spamming, que atenten contra la juventud o la infancia, el orden o la seguridad p&uacute;blica o que, a su juicio, no resultaran adecuados para su publicaci&oacute;n.</p>
<p>En cualquier caso,&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;no ser&aacute; responsable de las opiniones vertidas por los Usuarios a trav&eacute;s de comentarios u otras herramientas de blogging o de participaci&oacute;n que pueda haber.</p>
<p>El mero acceso a este Sitio Web no supone entablar ning&uacute;n tipo de relaci&oacute;n de car&aacute;cter comercial entre&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;y el Usuario.</p>
<p>El Usuario declara ser mayor de edad y disponer de la capacidad jur&iacute;dica suficiente para vincularse por las presentes Condiciones. Por lo tanto, este Sitio Web de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;no se dirige a menores de edad.&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;declina cualquier responsabilidad por el incumplimiento de este requisito.</p>
<h3>III. ACCESO Y NAVEGACI&Oacute;N EN EL SITIO WEB: EXCLUSI&Oacute;N DE GARANT&Iacute;AS Y RESPONSABILIDAD</h3>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;no garantiza la continuidad, disponibilidad y utilidad del Sitio Web, ni de los Contenidos o Servicios.&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;har&aacute; todo lo posible por el buen funcionamiento del Sitio Web, sin embargo, no se responsabiliza ni garantiza que el acceso a este Sitio Web no vaya a ser ininterrumpido o que est&eacute; libre de error.</p>
<p>Tampoco se responsabiliza o garantiza que el contenido o software al que pueda accederse a trav&eacute;s de este Sitio Web, est&eacute; libre de error o cause un da&ntilde;o al sistema inform&aacute;tico (software y hardware) del Usuario. En ning&uacute;n caso&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;ser&aacute; responsable por las p&eacute;rdidas, da&ntilde;os o perjuicios de cualquier tipo que surjan por el acceso, navegaci&oacute;n y el uso del Sitio Web, incluy&eacute;ndose, pero no limit&aacute;ndose, a los ocasionados a los sistemas inform&aacute;ticos o los provocados por la introducci&oacute;n de virus.</p>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;tampoco se hace responsable de los da&ntilde;os que pudiesen ocasionarse a los usuarios por un uso inadecuado de este Sitio Web. En particular, no se hace responsable en modo alguno de las ca&iacute;das, interrupciones, falta o defecto de las telecomunicaciones que pudieran ocurrir.</p>
<h3>IV. POL&Iacute;TICA DE ENLACES</h3>
<p>Se informa que el Sitio Web de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;pone o puede poner a disposici&oacute;n de los Usuarios medios de enlace (como, entre otros, links, banners, botones), directorios y motores de b&uacute;squeda que permiten a los Usuarios acceder a sitios web pertenecientes y/o gestionados por terceros.</p>
<p>La instalaci&oacute;n de estos enlaces, directorios y motores de b&uacute;squeda en el Sitio Web tiene por objeto facilitar a los Usuarios la b&uacute;squeda de y acceso a la informaci&oacute;n disponible en Internet, sin que pueda considerarse una sugerencia, recomendaci&oacute;n o invitaci&oacute;n para la visita de los mismos.</p>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;no ofrece ni comercializa por s&iacute; ni por medio de terceros los productos y/o servicios disponibles en dichos sitios enlazados.</p>
<p>Asimismo, tampoco garantizar&aacute; la disponibilidad t&eacute;cnica, exactitud, veracidad, validez o legalidad de sitios ajenos a su propiedad a los que se pueda acceder por medio de los enlaces.</p>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;en ning&uacute;n caso revisar&aacute; o controlar&aacute; el contenido de otros sitios web, as&iacute; como tampoco aprueba, examina ni hace propios los productos y servicios, contenidos, archivos y cualquier otro material existente en los referidos sitios enlazados.</p>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;no asume ninguna responsabilidad por los da&ntilde;os y perjuicios que pudieran producirse por el acceso, uso, calidad o licitud de los contenidos, comunicaciones, opiniones, productos y servicios de los sitios web no gestionados por&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;y que sean enlazados en este Sitio Web.</p>
<p>El Usuario o tercero que realice un hiperv&iacute;nculo desde una p&aacute;gina web de otro, distinto, sitio web al Sitio Web de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;deber&aacute; saber que:</p>
<p>No se permite la reproducci&oacute;n &mdash;total o parcialmente&mdash; de ninguno de los Contenidos y/o Servicios del Sitio Web sin autorizaci&oacute;n expresa de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>.</p>
<p>No se permite tampoco ninguna manifestaci&oacute;n falsa, inexacta o incorrecta sobre el Sitio Web de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>, ni sobre los Contenidos y/o Servicios del mismo.</p>
<p>A excepci&oacute;n del hiperv&iacute;nculo, el sitio web en el que se establezca dicho hiperenlace no contendr&aacute; ning&uacute;n elemento, de este Sitio Web, protegido como propiedad intelectual por el ordenamiento jur&iacute;dico espa&ntilde;ol, salvo autorizaci&oacute;n expresa de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>.</p>
<p>El establecimiento del hiperv&iacute;nculo no implicar&aacute; la existencia de relaciones entre&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;y el titular del sitio web desde el cual se realice, ni el conocimiento y aceptaci&oacute;n de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;de los contenidos, servicios y/o actividades ofrecidas en dicho sitio web, y viceversa.</p>
<h3>V. PROPIEDAD INTELECTUAL E INDUSTRIAL</h3>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;por s&iacute; o como parte cesionaria, es titular de todos los derechos de propiedad intelectual e industrial del Sitio Web, as&iacute; como de los elementos contenidos en el mismo (a t&iacute;tulo enunciativo y no exhaustivo, im&aacute;genes, sonido, audio, v&iacute;deo, software o textos, marcas o logotipos, combinaciones de colores, estructura y dise&ntilde;o, selecci&oacute;n de materiales usados, programas de ordenador necesarios para su funcionamiento, acceso y uso, etc.). Ser&aacute;n, por consiguiente, obras protegidas como propiedad intelectual por el ordenamiento jur&iacute;dico espa&ntilde;ol, si&eacute;ndoles aplicables tanto la normativa espa&ntilde;ola y comunitaria en este campo, como los tratados internacionales relativos a la materia y suscritos por Espa&ntilde;a.</p>
<p>Todos los derechos reservados. En virtud de lo dispuesto en la Ley de Propiedad Intelectual, quedan expresamente prohibidas la reproducci&oacute;n, la distribuci&oacute;n y la comunicaci&oacute;n p&uacute;blica, incluida su modalidad de puesta a disposici&oacute;n, de la totalidad o parte de los contenidos de esta p&aacute;gina web, con fines comerciales, en cualquier soporte y por cualquier medio t&eacute;cnico, sin la autorizaci&oacute;n de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>.</p>
<p>El Usuario se compromete a respetar los derechos de propiedad intelectual e industrial de&nbsp;<span class="blanc-space ng-binding">Lucecine</span>. Podr&aacute; visualizar los elementos del Sitio Web o incluso imprimirlos, copiarlos y almacenarlos en el disco duro de su ordenador o en cualquier otro soporte f&iacute;sico siempre y cuando sea, exclusivamente, para su uso personal. El Usuario, sin embargo, no podr&aacute; suprimir, alterar, o manipular cualquier dispositivo de protecci&oacute;n o sistema de seguridad que estuviera instalado en el Sitio Web.</p>
<p>En caso de que el Usuario o tercero considere que cualquiera de los Contenidos del Sitio Web suponga una violaci&oacute;n de los derechos de protecci&oacute;n de la propiedad intelectual, deber&aacute; comunicarlo inmediatamente a&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;a trav&eacute;s de los datos de contacto del apartado de INFORMACI&Oacute;N GENERAL de este Aviso Legal y Condiciones Generales de Uso.</p>
<h3>VI. ACCIONES LEGALES, LEGISLACI&Oacute;N APLICABLE Y JURISDICCI&Oacute;N</h3>
<p><span class="blanc-space ng-binding">Lucecine</span>&nbsp;se reserva la facultad de presentar las acciones civiles o penales que considere necesarias por la utilizaci&oacute;n indebida del Sitio Web y Contenidos, o por el incumplimiento de las presentes Condiciones.</p>
<p>La relaci&oacute;n entre el Usuario y&nbsp;<span class="blanc-space ng-binding">Lucecine</span>&nbsp;se regir&aacute; por la normativa vigente y de aplicaci&oacute;n en el territorio espa&ntilde;ol. De surgir cualquier controversia en relaci&oacute;n con la interpretaci&oacute;n y/o a la aplicaci&oacute;n de estas Condiciones las partes someter&aacute;n sus conflictos a la jurisdicci&oacute;n ordinaria someti&eacute;ndose a los jueces y tribunales que correspondan conforme a derecho.</p>
</div>
<header style="text-align: center !important;color: rgb(33, 37, 41);font-size: 16px;"><strong>
        <h2 style="font-size: 2rem;">CONDICIONES GENERALES DE VENTA</h2>
    </strong><strong>
        <h4 style="font-size: 1.5rem;"><span style="border-bottom: 1px solid rgb(0, 0, 0);">www.lucecine.com</span></h4>
    </strong></header>
<div style="text-align: start;color: rgb(33, 37, 41);font-size: 16px;"><strong>
        <h3 style="font-size: 1.7rem;">1. INFORMACI&Oacute;N GENERAL</h3>
    </strong>
    <p>La titularidad de este sitio web <span style="border-bottom: 1px solid rgb(0, 0, 0);">www.lucecine.com</span>, (en adelante Sitio Web) la ostenta: <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine S.L.</span>, provista de NIF: <span style="border-bottom: 1px solid rgb(0, 0, 0);">A-80080000</span> e inscrita en: <span style="border-bottom: 1px solid rgb(0, 0, 0);">Registro Mercantil de C&oacute;rdoba</span>; y cuyos datos registrales son: <span style="border-bottom: 1px solid rgb(0, 0, 0);">Tomo 0, P&aacute;gina 9, Hoja 888</span>, y cuyos datos de contacto son:</p>
    <p>Direcci&oacute;n: <span style="border-bottom: 1px solid rgb(0, 0, 0);">C/Torremolinos, N&ordm;13, 28821 - Coslada (Madrid)</span></p>
    <p>Tel&eacute;fono de contacto: <span style="border-bottom: 1px solid rgb(0, 0, 0);">961111111</span></p>
    <p>Fax: <span style="border-bottom: 1px solid rgb(0, 0, 0);">968850000</span></p>
    <p>Email de contacto: <span style="border-bottom: 1px solid rgb(0, 0, 0);">lucecine@gmail.com</span></p>
    <p>Este documento (as&iacute; como otros documentos que aqu&iacute; se mencionen) regula las condiciones por las que se rige el uso de este Sitio Web (<span style="border-bottom: 1px solid rgb(0, 0, 0);">www.lucecine.com</span>) y la compra o adquisici&oacute;n de productos y/o servicios en el mismo (en adelante, Condiciones).</p>
    <p>A efectos de estas Condiciones se entiende que la actividad que <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> desarrolla a trav&eacute;s del Sitio Web comprende:</p>
    <p><span style="border-bottom: 1px solid rgb(0, 0, 0);">Suscripci&oacute;n mensual del servicio premium de la p&aacute;gina web</span></p>
    <p>Adem&aacute;s de leer las presentes Condiciones, antes de acceder, navegar y/o usar esta p&aacute;gina web, el Usuario ha de haber le&iacute;do el Aviso Legal y las Condiciones Generales de Uso, incluyendo, la pol&iacute;tica de cookies, y la pol&iacute;tica de privacidad y de protecci&oacute;n de datos de <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span>. Al utilizar este Sitio Web o al hacer y/o solicitar la adquisici&oacute;n de un producto y/o servicio a trav&eacute;s del mismo el Usuario consiente quedar vinculado por estas Condiciones y por todo lo anteriormente mencionado, por lo que si no est&aacute; de acuerdo con todo ello, no debe usar este Sitio Web.</p>
    <p>Asimismo, se informa que estas Condiciones podr&iacute;an ser modificadas. El Usuario es responsable de consultarlas cada vez que acceda, navegue y/o use el Sitio Web ya que ser&aacute;n aplicables aquellas que se encuentren vigentes en el momento en que se solicite la adquisici&oacute;n de productos y/o servicios.</p>
    <p>Para todas las preguntas que el Usuario pueda tener en relaci&oacute;n con las Condiciones puede ponerse en contacto con el titular utilizando los datos de contacto facilitados m&aacute;s arriba o, en su caso, utilizando el formulario de contacto.</p><strong>
        <h3 style="font-size: 1.7rem;">2. EL USUARIO</h3>
    </strong>
    <p>El acceso, la navegaci&oacute;n y uso del Sitio Web, confiere la condici&oacute;n de usuario (en adelante referido, indistintamente, individualmente como Usuario o conjuntamente como Usuarios), por lo que se aceptan, desde que se inicia la navegaci&oacute;n por el Sitio Web, todas las Condiciones aqu&iacute; establecidas, as&iacute; como sus ulteriores modificaciones, sin perjuicio de la aplicaci&oacute;n de la correspondiente normativa legal de obligado cumplimiento seg&uacute;n el caso.</p>
    <p>El Usuario asume su responsabilidad de un uso correcto del Sitio Web. Esta responsabilidad se extender&aacute; a:</p>
    <ul>
        <li>
            <p>Hacer uso de este Sitio Web &uacute;nicamente para realizar consultas y compras o adquisiciones legalmente v&aacute;lidas.</p>
        </li>
        <li>
            <p>No realizar ninguna compra falsa o fraudulenta. Si razonablemente se pudiera considerar que se ha hecho una compra de esta &iacute;ndole, podr&iacute;a ser anulada y se informar&iacute;a a las autoridades pertinentes.</p>
        </li>
        <li>
            <p>Facilitar datos de contacto veraces y l&iacute;citos, por ejemplo, direcci&oacute;n de correo electr&oacute;nico, direcci&oacute;n postal y/u otros datos (ver Aviso Legal y Condiciones Generales de Uso).</p>
        </li>
    </ul>
    <p>El Usuario declara ser mayor de 18 a&ntilde;os y tener capacidad legal para celebrar contratos a trav&eacute;s de este Sitio Web.</p>
    <p>El Usuario podr&aacute; formalizar, a su elecci&oacute;n, con <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> el contrato de compraventa de los productos y/o servicios deseados en cualquiera de los idiomas en los que las presentes Condiciones est&eacute;n disponibles en este Sitio Web.</p><strong>
        <h3 style="font-size: 1.7rem;">3. PROCESO DE COMPRA O ADQUISICI&Oacute;N</h3>
    </strong>
    <p>Los Usuarios pueden comprar en el Sitio Web por los medios y formas establecidos. Deber&aacute;n seguir el procedimiento de compra y/o adquisici&oacute;n online de <span style="border-bottom: 1px solid rgb(0, 0, 0);">www.lucecine.com</span>, durante el cual varios productos y/o servicios pueden ser seleccionados y a&ntilde;adidos al carrito, cesta o espacio final de compra y, finalmente, hacer clic en: &quot;<span style="border-bottom: 1px solid rgb(0, 0, 0);">Confirmar suscripci&oacute;n</span>&quot;</p>
    <p>Asimismo, el Usuario deber&aacute; rellenar y/o comprobar la informaci&oacute;n que en cada paso se le solicita, aunque, durante el proceso de compra, antes de realizar el pago, se pueden modificar los datos de la compra.</p>
    <p>Seguidamente, el Usuario recibir&aacute; un correo electr&oacute;nico confirmando que <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> ha recibido su pedido o solicitud de compra y/o prestaci&oacute;n del servicio, es decir, la confirmaci&oacute;n del pedido. Y, en su caso, se le informar&aacute;, igualmente, mediante correo electr&oacute;nico cuando su compra est&eacute; siendo enviada. En su caso, estas informaciones tambi&eacute;n podr&iacute;an ponerse a disposici&oacute;n del Usuario a trav&eacute;s de su espacio personal de conexi&oacute;n al Sitio Web.</p>
    <p>Una vez el procedimiento de compra ha concluido, el Usuario consiente que el Sitio Web genere una factura electr&oacute;nica que se har&aacute; llegar al Usuario a trav&eacute;s del correo electr&oacute;nico&nbsp;y en su caso, a trav&eacute;s de su espacio personal de conexi&oacute;n al Sitio Web. Asimismo, el Usuario puede, si as&iacute; lo desea, obtener una copia de su factura en papel, solicit&aacute;ndolo a <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> utilizando los espacios de contacto del Sitio Web o a trav&eacute;s de los datos de contacto facilitados m&aacute;s arriba.</p>
    <p>El Usuario reconoce estar al corriente, en el momento de la compra, de ciertas condiciones particulares de venta que conciernen al producto y/o servicio en cuesti&oacute;n y que se muestran junto a la presentaci&oacute;n o, en su caso, imagen de &eacute;ste en su p&aacute;gina del Sitio Web, indicando, a modo enunciativo, pero no exhaustivo, y atendiendo a cada caso: nombre, precio, componentes, peso, cantidad, color, detalles de los productos, o caracter&iacute;sticas, modo en el que se llevar&aacute;n a cabo y/o coste de las prestaciones; y reconoce que la realizaci&oacute;n del pedido de compra o adquisici&oacute;n materializa la aceptaci&oacute;n plena y completa de las condiciones particulares de venta aplicables a cada caso.</p>
    <p>Las comunicaciones, &oacute;rdenes de compra y pagos que intervengan durante las transacciones efectuadas en el Sitio Web podr&iacute;an ser archivadas y conservadas en los registros informatizados de <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> con el fin de constituir un medio de prueba de las transacciones, en todo caso, respetando las condiciones razonables de seguridad y las leyes y normativas vigentes que a este respecto sean de aplicaci&oacute;n, y particularmente atendiendo al Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales y a la libre circulaci&oacute;n de estos datos (RGPD) y la Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales, y a los derechos que asisten a los Usuarios conforme a la pol&iacute;tica de privacidad de este Sitio Web.</p><strong>
        <h3 style="font-size: 1.7rem;">4. DISPONIBILIDAD</h3>
    </strong>
    <p>Todos los pedidos de compra recibidos por <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> a trav&eacute;s del Sitio Web est&aacute;n sujetos a la disponibilidad de los productos y/o a que ninguna circunstancia o causa de fuerza mayor (cl&aacute;usula nueve de estas Condiciones) afecte al suministro de los mismos y/o a la prestaci&oacute;n de los servicios. Si se produjeran dificultades en cuanto al suministro de productos o no quedaran productos en stock, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> se compromete a contactar al Usuario y reembolsar cualquier cantidad que pudiera haber sido abonada en concepto de importe. Esto ser&aacute; igualmente aplicable en los casos en los que la prestaci&oacute;n de un servicio deviniera irrealizable.</p><strong>
        <h3 style="font-size: 1.7rem;">5. PRECIOS Y PAGO</h3>
    </strong>
    <p>Los precios exhibidos en el Sitio Web son los finales, en Euros (&euro;) e incluyen los impuestos, salvo que por exigencia legal, especialmente en lo relativo al IVA, se se&ntilde;ale y aplique cuesti&oacute;n distinta.</p>
    <p>No obstante, y salvo que se indique, puntualmente otra cosa, los precios de los art&iacute;culos ofrecidos excluyen los gastos de env&iacute;o, en los que se pudiera incurrir, que se a&ntilde;adir&aacute;n al importe total debido al momento de gestionar el procedimiento de env&iacute;o por parte del Usuario, y donde &eacute;ste consultar&aacute; los m&eacute;todos y costes de env&iacute;o disponibles y elegir&aacute; libremente el que m&aacute;s le convenga.</p>
    <p>En ning&uacute;n caso el Sitio Web a&ntilde;adir&aacute; costes adicionales al precio de un producto o de un servicio de forma autom&aacute;tica, sino solo aquellos que el Usuario haya seleccionado y elegido voluntaria y libremente.</p>
    <p>Los precios pueden cambiar en cualquier momento, pero los posibles cambios no afectar&aacute;n a los pedidos o compras con respecto a los que el Usuario ya haya&nbsp;recibido una confirmaci&oacute;n de pedido.</p>
    <p>Los medios de pago aceptados ser&aacute;n:&nbsp;Tarjeta de cr&eacute;dito o d&eacute;bito</p>
    <p>Las tarjetas de cr&eacute;dito estar&aacute;n sujetas a comprobaciones y autorizaciones por parte de la entidad bancaria emisora de las mismas, si dicha entidad no autorizase el pago, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> no ser&aacute; responsable por ning&uacute;n retraso o falta de entrega y no podr&aacute; formalizar ning&uacute;n contrato con el Usuario.</p>
    <p>Una vez que <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> reciba la orden de compra por parte del Usuario a trav&eacute;s del Sitio Web, se har&aacute; una pre-autorizaci&oacute;n en la tarjeta que corresponda para asegurar que existen fondos suficientes para completar la transacci&oacute;n. El cargo en la tarjeta se har&aacute; en el momento en que se env&iacute;e al Usuario la confirmaci&oacute;n de env&iacute;o y/o confirmaci&oacute;n del servicio que se presta en forma y, en su caso, lugar establecidos.</p>
    <p>En todo caso, al hacer clic en &quot;<span style="border-bottom: 1px solid rgb(0, 0, 0);">Confirmar suscripci&oacute;n</span>&quot; el Usuario confirma que el m&eacute;todo de pago utilizado es suyo.</p><strong>
        <h3 style="font-size: 1.7rem;">6. ENTREGA</h3>
    </strong>
    <p>En los casos en los que proceda realizar la entrega f&iacute;sica del bien contratado, las entregas se efectuar&aacute;n en el &aacute;mbito del siguiente territorio:&nbsp;Espa&ntilde;a (Pen&iacute;nsula y Baleares)</p>
    <p>Exceptuando aquellos casos en los que existan circunstancias imprevistas o extraordinarias o, en su caso, derivadas de la personalizaci&oacute;n de los productos, el pedido de compra consistente en los productos relacionados en cada confirmaci&oacute;n de compra ser&aacute; entregado en el plazo se&ntilde;alado en el Sitio Web seg&uacute;n el m&eacute;todo de env&iacute;o seleccionado por el Usuario y, en todo caso, en el plazo m&aacute;ximo de 30 d&iacute;as naturales a contar desde la fecha de la confirmaci&oacute;n del pedido.</p>
    <p>Si por alg&uacute;n motivo, que le fuera imputable, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> no pudiera cumplir con la fecha de entrega, contactar&aacute; al Usuario para informarle de esta circunstancia y, &eacute;ste podr&aacute; elegir seguir adelante con la compra estableciendo una nueva fecha de entrega o bien anular el pedido con el reembolso total del precio pagado. En cualquier caso, las entregas a domicilio se realizan en d&iacute;as laborables.</p>
    <p>Si resultara imposible efectuar la entrega del pedido por ausencia del Usuario, el pedido podr&iacute;a ser devuelto al almac&eacute;n. No obstante, el transportista dejar&iacute;a un aviso explicando d&oacute;nde se encuentra el pedido y c&oacute;mo hacer para que sea entregado de nuevo.</p>
    <p>Si el Usuario no va a estar en el lugar de entrega en la franja horaria convenida, debe ponerse en contacto con <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> para convenir la entrega otro d&iacute;a.</p>
    <p>En caso de que transcurran 30 d&iacute;as desde que su pedido est&eacute; disponible para su entrega, y no haya sido entregado por causa no imputable a <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span>, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> entender&aacute; que el Usuario desea desistir del contrato y &eacute;ste se considerar&aacute; resuelto. Como consecuencia de la resoluci&oacute;n del contrato, todos los pagos recibidos del Usuario le ser&aacute;n devueltos, a excepci&oacute;n de los gastos adicionales resultantes de la elecci&oacute;n propia del Usuario de una modalidad de entrega diferente a la modalidad menos costosa de entrega ordinaria que ofrece el Sitio Web, sin ninguna demora indebida y, en cualquier caso, en el plazo m&aacute;ximo de 14 d&iacute;as naturales desde la fecha en que se considera resuelto el contrato.</p>
    <p>No obstante, el Usuario debe tener presente que el transporte derivado de la resoluci&oacute;n puede tener un coste adicional que le podr&aacute; ser repercutido.</p>
    <p>A efectos de las presentes Condiciones, se entender&aacute; que se ha producido la entrega o que el pedido ha sido entregado en el momento en el que el Usuario o un tercero indicado por el Usuario adquiera la posesi&oacute;n material de los productos, lo que se acreditar&aacute; mediante la firma de la recepci&oacute;n del pedido en la direcci&oacute;n de entrega convenida.</p>
    <p>Los riesgos que de los productos se pudieran derivar ser&aacute;n a cargo del Usuario a partir del momento de su entrega. El Usuario adquiere la propiedad de los productos cuando <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> recibe el pago completo de todas las cantidades debidas en relaci&oacute;n a la compra o adquisici&oacute;n efectuada, incluidos los gastos de env&iacute;o, o bien en el momento de la entrega, si &eacute;sta tiene lugar en un momento posterior a la recepci&oacute;n completa del importe objeto de pago por <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span>.</p>
    <p>De conformidad con lo dispuesto en la Ley 37/1992, de 28 de diciembre, del Impuesto sobre el Valor A&ntilde;adido (IVA), los pedidos de compra para su entrega y/o prestaci&oacute;n se entender&aacute;n localizados en el territorio de aplicaci&oacute;n del IVA espa&ntilde;ol si la direcci&oacute;n de entrega est&aacute; en territorio espa&ntilde;ol salvo Canarias, Ceuta y Melilla. El tipo de IVA aplicable ser&aacute; el legalmente vigente en cada momento en funci&oacute;n del art&iacute;culo concreto de que se trate.</p><strong>
        <h3 style="font-size: 1.7rem;">7. MEDIOS T&Eacute;CNICOS PARA CORREGIR ERRORES</h3>
    </strong>
    <p>Se pone en conocimiento del Usuario que en caso de que detecte que se ha producido un error al introducir datos necesarios para procesar su solicitud de compra en el Sitio Web, podr&aacute; modificar los mismos poni&eacute;ndose en contacto con <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> a trav&eacute;s de los espacios de contacto habilitados en el Sitio Web, y, en su caso, a trav&eacute;s de aquellos habilitados para contactar con el servicio de atenci&oacute;n al cliente, y/o utilizando los datos de contacto facilitados en la cl&aacute;usula primera (Informaci&oacute;n general). Asimismo, estas informaciones tambi&eacute;n podr&iacute;an subsanarse por el Usuario a trav&eacute;s de su espacio personal de conexi&oacute;n al Sitio Web.</p>
    <p>En cualquier caso, el Usuario, antes de hacer clic en &quot;<span style="border-bottom: 1px solid rgb(0, 0, 0);">Confirmar suscripci&oacute;n</span>&quot;, tiene acceso al espacio, carrito, o cesta donde se van anotando sus solicitudes de compra y puede hacer modificaciones.</p>
    <p>De igual forma, se remite al Usuario a consultar el Aviso Legal y Condiciones Generales de Uso y, en concreto, la Pol&iacute;tica de Privacidad para recabar m&aacute;s informaci&oacute;n sobre c&oacute;mo ejercer su derecho de rectificaci&oacute;n seg&uacute;n lo establecido en el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales y a la libre circulaci&oacute;n de estos datos (RGPD) y en la Ley Org&aacute;nica 3/2018, de 5 de diciembre, de Protecci&oacute;n de Datos Personales y garant&iacute;a de los derechos digitales.</p><strong>
        <h3 style="font-size: 1.7rem;">8. DEVOLUCIONES</h3>
    </strong>
    <p>En los casos en los que el Usuario adquiriera productos en o trav&eacute;s del Sitio Web del titular, le asisten una serie de derechos, tal y como se enumeran y describen a continuaci&oacute;n:</p><strong>
        <h4 style="font-size: 1.5rem;">Derecho de Desistimiento</h4>
    </strong>
    <p>El Usuario, en tanto que consumidor y usuario, realiza una compra en el Sitio Web y, por tanto le asiste el derecho a desistir de dicha compra en un plazo de 14 d&iacute;as naturales sin necesidad de justificaci&oacute;n.</p>
    <p>Este plazo de desistimiento expirar&aacute; a los 14 d&iacute;as naturales del d&iacute;a que el Usuario o un tercero autorizado por &eacute;ste, distinto del transportista, adquiri&oacute; la posesi&oacute;n material de los bienes adquiridos en el Sitio Web de <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> o en caso de que los bienes que componen su pedido se entreguen por separado, a los 14 d&iacute;as naturales del d&iacute;a que el Usuario o un tercero autorizado por &eacute;ste, distinto del transportista, adquiri&oacute; la posesi&oacute;n material del &uacute;ltimo de esos bienes que compon&iacute;an un mismo pedido de compra, o en el caso de tratarse de un contrato de servicios, a los 14 d&iacute;as naturales desde el d&iacute;a de la celebraci&oacute;n del contrato.</p>
    <p>Para ejercer este derecho de desistimiento, el Usuario deber&aacute; notificar su decisi&oacute;n a <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span>. Podr&aacute; hacerlo, en su caso, a trav&eacute;s de los espacios de contacto habilitados en el Sitio Web.</p>
    <p>El Usuario, independientemente del medio que elija para comunicar su decisi&oacute;n, debe expresar de forma clara e inequ&iacute;voca que es su intenci&oacute;n desistir del contrato de compra. En todo caso, el Usuario podr&aacute; utilizar el modelo de formulario de desistimiento que <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> pone a su disposici&oacute;n como parte anexada a estas Condiciones, sin embargo, su uso no es obligatorio.</p>
    <p>Para cumplir el plazo de desistimiento, basta con que la comunicaci&oacute;n que expresa inequ&iacute;vocamente la decisi&oacute;n de desistir sea enviada antes de que venza el plazo correspondiente.</p>
    <p>En caso de desistimiento, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> reembolsar&aacute; al Usuario todos los pagos recibidos, incluidos los gastos de env&iacute;o (con la excepci&oacute;n de los gastos adicionales elegidos por el Usuario para una modalidad de env&iacute;o diferente a la modalidad menos costosa ofrecida en el Sitio Web) sin ninguna demora indebida y, en todo caso, a m&aacute;s tardar en 14 d&iacute;as naturales a partir de la fecha en la que <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> es informado de la decisi&oacute;n de desistir por el Usuario.</p>
    <p><span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> reembolsar&aacute; al Usuario utilizando el mismo m&eacute;todo de pago que emple&oacute; este para realizar la transacci&oacute;n inicial de compra. Este reembolso no generar&aacute; ning&uacute;n coste adicional al Usuario. No obstante, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> podr&iacute;a retener dicho reembolso hasta haber recibido los productos o art&iacute;culos de la compra, o hasta que el Usuario presente una prueba de la devoluci&oacute;n de los mismos, seg&uacute;n qu&eacute; condici&oacute;n se cumpla primero.</p>
    <p>El Usuario puede devolver o enviar los productos a <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> en: <span style="border-bottom: 1px solid rgb(0, 0, 0);">C/Torremolinos, N&ordm;13, 28821 - Coslada (Madrid)</span></p>
    <p>Y deber&aacute; hacerlo sin ninguna demora indebida y, en cualquier caso, a m&aacute;s tardar en el plazo de 14 d&iacute;as naturales a partir de la fecha en que <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> fue informado de la decisi&oacute;n de desistimiento.</p>
    <p>El Usuario reconoce conocer que deber&aacute; asumir el coste directo de devoluci&oacute;n (transporte, entrega) de los bienes, si se incurriera en alguno. Adem&aacute;s, ser&aacute; responsable de la disminuci&oacute;n de valor de los productos resultante de una manipulaci&oacute;n distinta a la necesaria para establecer la naturaleza, las caracter&iacute;sticas y el funcionamiento de los bienes.</p>
    <p>El Usuario reconoce saber que existen excepciones al derecho de desistimiento, tal y como se recoge en el art&iacute;culo 103 del Real Decreto Legislativo 1/2007, de 16 de noviembre, por el que se aprueba el texto refundido de la Ley General para la Defensa de los Consumidores y Usuarios y otras leyes complementarias. De forma enunciativa, y no exhaustiva, este ser&iacute;a el caso de: productos personalizados; productos que puedan deteriorarse o caducar con rapidez; CDs/DVD de m&uacute;sica o video sin su envoltorio, tal y como se precinta en f&aacute;brica; productos que por razones de higiene o de la salud van precintados y han sido desprecintados tras la entrega; suministro de contenido digital sin soporte f&iacute;sico.</p>
    <p>En este mismo sentido se rige la prestaci&oacute;n de un servicio que el Usuario pudiera contratar en este Sitio Web, pues esta misma Ley establece que no asistir&aacute; el Derecho de desistimiento a los Usuarios cuando la prestaci&oacute;n del servicio ha sido completamente ejecutada, o cuando haya comenzado, con el consentimiento expreso del consumidor y usuario y con el reconocimiento por su parte de que es consciente de que, una vez que el contrato haya sido completamente ejecutado por <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span>, habr&aacute; perdido su derecho de desistimiento.</p>
    <p>En todo caso, no se har&aacute; ning&uacute;n reembolso si el producto ha sido usado m&aacute;s all&aacute; de la mera apertura del mismo, de productos que no est&eacute;n en las mismas condiciones en las que se entregaron o que hayan sufrido alg&uacute;n da&ntilde;o tras la entrega.</p>
    <p>Asimismo, se debe devolver los productos usando o incluyendo todos sus envoltorios originales, las instrucciones y dem&aacute;s documentos que en su caso los acompa&ntilde;en, adem&aacute;s de una copia de la factura de compra.</p>
    <p>En el siguiente enlace puede descargarse el Modelo de formulario de desistimiento: <span style="border-bottom: 1px solid rgb(0, 0, 0);">https://www.sitioweb.com/modelodesistimiento/</span></p><strong>
        <h4 style="font-size: 1.5rem;">Devoluci&oacute;n de productos defectuosos o error en el env&iacute;o</h4>
    </strong>
    <p>Se trata de todos aquellos casos en los que el Usuario considera que, en el momento de la entrega, el producto no se ajusta a lo estipulado en el contrato o pedido de compra, y que, por tanto, deber&aacute; ponerse en contacto con <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> inmediatamente y hacerle saber la disconformidad existente (defecto/error) por los mismos medios o utilizando los datos de contacto que se facilitan en el apartado anterior (Derecho de Desistimiento).</p>
    <p>El Usuario ser&aacute; entonces informado sobre c&oacute;mo proceder a la devoluci&oacute;n de los productos, y estos, una vez devueltos, ser&aacute;n examinados y se informar&aacute; al Usuario, dentro de un plazo razonable, si procede el reembolso o, en su caso, la sustituci&oacute;n del mismo.</p>
    <p>El reembolso o la sustituci&oacute;n del producto se efectuar&aacute; lo antes posible y, en cualquier caso, dentro de los 14 d&iacute;as siguientes a la fecha en la que le enviemos un correo electr&oacute;nico confirmando que procede el reembolso o la sustituci&oacute;n del art&iacute;culo no conforme.</p>
    <p>El importe abonado por aquellos productos que sean devueltos a causa de alg&uacute;n defecto, cuando realmente exista, ser&aacute; reembolsado &iacute;ntegramente, incluidos los gastos de entrega y los costes en que hubiera podido incurrir el Usuario para realizar la devoluci&oacute;n. El reembolso se efectuar&aacute; por el mismo medio de pago que el Usuario utiliz&oacute; para pagar la compra.</p>
    <p>En todo caso, se estar&aacute; siempre a los derechos reconocidos en la legislaci&oacute;n vigente en cada momento para el Usuario, en tanto que consumidor y usuario.</p><strong>
        <h4 style="font-size: 1.5rem;">Garant&iacute;as</h4>
    </strong>
    <p>El Usuario, en tanto que consumidor y usuario, goza de garant&iacute;as sobre los productos que pueda adquirir a trav&eacute;s de este Sitio Web, en los t&eacute;rminos legalmente establecidos para cada tipo de producto, respondiendo <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span>, por tanto, por la falta de conformidad de los mismos que se manifieste en un plazo de tres a&ntilde;os desde la entrega del producto.</p>
    <p>En este sentido, se entiende que los productos son conformes con el contrato siempre que: se ajusten a la descripci&oacute;n realizada por <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> y posean las cualidades presentadas en la misma; sean aptos para los usos a que ordinariamente se destinan los productos del mismo tipo; y presenten la calidad y prestaciones habituales de un producto del mismo tipo y que sean fundamentalmente esperables del mismo. Cuando esto no sea as&iacute; respecto de los productos entregados al Usuario, &eacute;ste deber&aacute; proceder tal y como se indica en el apartado Devoluci&oacute;n de productos defectuosos o error en el env&iacute;o. No obstante, algunos de los productos que se comercializan en el Sitio Web, podr&iacute;an presentar caracter&iacute;sticas no homog&eacute;neas siempre y cuando &eacute;stas deriven del tipo de material con el que se han fabricado, y que por ende formar&aacute;n parte de la apariencia individual del producto, y no ser&aacute;n un defecto.</p>
    <p>Por otra parte, podr&iacute;a llegar a darse el caso que el Usuario adquiere en el Sitio Web un producto de una marca o de fabricaci&oacute;n por un tercero. En este caso, y considerando el Usuario que se trata de un producto defectuoso, &eacute;ste tambi&eacute;n tiene la posibilidad de ponerse en contacto con la marca o fabricante responsable del producto para averiguar c&oacute;mo ejercer su derecho de garant&iacute;a legal directamente frente a los mismos durante los tres a&ntilde;os siguientes a la entrega de dichos productos. Para ello, el Usuario debe haber conservado toda la informaci&oacute;n en relaci&oacute;n con la garant&iacute;a de los productos.</p>
    <p>No obstante, para conocer m&aacute;s sobre el Servicio Posventa que <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> pone al servicio de los Usuarios del el Sitio Web puede consultarlo aqu&iacute;: <span style="border-bottom: 1px solid rgb(0, 0, 0);">https://www.sitioweb.com/soporte/</span></p><strong>
        <h3 style="font-size: 1.7rem;">9. EXONERACI&Oacute;N DE RESPONSABILIDAD</h3>
    </strong>
    <p>Salvo disposici&oacute;n legal en sentido contrario, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> no aceptar&aacute; ninguna responsabilidad por las siguientes p&eacute;rdidas, con independencia de su origen:</p>
    <ul>
        <li>
            <p>cualesquiera p&eacute;rdidas que no fueran atribuibles a incumplimiento alguno por su parte;</p>
        </li>
        <li>
            <p>p&eacute;rdidas empresariales (incluyendo lucro cesante, de ingresos, de contratos, de ahorros previstos, de datos, p&eacute;rdida del fondo de comercio o gastos innecesarios incurridos); o de</p>
        </li>
        <li>
            <p>toda otra p&eacute;rdida indirecta que no fuera razonablemente previsible por ambas partes en el momento en que se formaliz&oacute; el contrato de compraventa de los productos entre ambas partes.</p>
        </li>
    </ul>
    <p>Igualmente, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> tambi&eacute;n limita su responsabilidad en cuanto a los siguientes casos:</p>
    <ul>
        <li><span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> aplica todas las medidas concernientes a proporcionar una visualizaci&oacute;n fiel del producto en el Sitio Web, sin embargo no se responsabiliza por las m&iacute;nimas diferencias o inexactitudes que puedan existir debido a falta de resoluci&oacute;n de la pantalla, o problemas del navegador que se utilice u otros de esta &iacute;ndole.</li>
        <li><span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> actuar&aacute; con la m&aacute;xima diligencia a efectos de poner a disposici&oacute;n de la empresa encargada del transporte del producto objeto del pedido de compra. Sin embargo, no se responsabiliza por perjuicios provenientes de un mal funcionamiento del transporte, especialmente por causas como huelgas, retenciones en carreteras, y en general cualquiera otras propias del sector, que deriven en retrasos, p&eacute;rdidas o hurtos del producto.</li>
        <li>Fallos t&eacute;cnicos que por causas fortuitas o de otra &iacute;ndole, impidan un normal funcionamiento del servicio a trav&eacute;s de internet. Falta de disponibilidad del Sitio Web por razones de mantenimiento u otras, que impida disponer del servicio. <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> pone todos los medios a su alcance a efectos de llevar a cabo el proceso de compra, pago y env&iacute;o/entrega de los productos, no obstante se exime de responsabilidad por causas que no le sean imputables, caso fortuito o fuerza mayor.</li>
        <li><span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> no se har&aacute; responsable del mal uso y/o del desgaste de los productos que hayan sido utilizados por el Usuario. Al mismo tiempo, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> tampoco se har&aacute; responsable de una devoluci&oacute;n err&oacute;nea realizada por el Usuario. Es responsabilidad del Usuario devolver el producto correcto.</li>
        <li>En general, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span>no se responsabilizar&aacute; por ning&uacute;n incumplimiento o retraso en el cumplimiento de alguna de las obligaciones asumidas, cuando el mismo se deba a acontecimientos que est&aacute;n fuera de su control razonable, es decir, que se deban a causa de fuerza mayor, y &eacute;sta podr&aacute; incluir, a modo enunciativo pero no exhaustivo:<ul>
                <li>Huelgas, cierres patronales u otras medidas reivindicativas.</li>
                <li>Conmoci&oacute;n civil, revuelta, invasi&oacute;n, amenaza o ataque terrorista, guerra (declarada o no) o amenaza o preparativos de guerra.</li>
                <li>Incendio, explosi&oacute;n, tormenta, inundaci&oacute;n, terremoto, hundimiento, epidemia o cualquier otro desastre natural.</li>
                <li>Imposibilidad de uso de trenes, barcos, aviones, transportes de motor u otros medios de transporte, p&uacute;blicos o privados.</li>
                <li>Imposibilidad de utilizar sistemas p&uacute;blicos o privados de telecomunicaciones.</li>
                <li>Actos, decretos, legislaci&oacute;n, normativa o restricciones de cualquier gobierno o autoridad p&uacute;blica.</li>
            </ul>
        </li>
    </ul>
    <p>De esta forma, las obligaciones quedar&aacute;n suspendidas durante el periodo en que la causa de fuerza mayor contin&uacute;e, y <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> dispondr&aacute; de una ampliaci&oacute;n en el plazo para cumplirlas por un periodo de tiempo igual al que dure la causa de fuerza mayor. <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> pondr&aacute; todos los medios razonables para encontrar una soluci&oacute;n que le permita cumplir con sus obligaciones a pesar de la causa de fuerza mayor.</p><strong>
        <h3 style="font-size: 1.7rem;">10. COMUNICACIONES POR ESCRITO Y NOTIFICACIONES</h3>
    </strong>
    <p>Mediante el uso de este Sitio Web, el Usuario acepta que la mayor parte de las comunicaciones con <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> sean electr&oacute;nicas (correo electr&oacute;nico o avisos publicados en el Sitio Web).</p>
    <p>A efectos contractuales, el Usuario consiente en usar este medio electr&oacute;nico de comunicaci&oacute;n y reconoce que todo contrato, notificaci&oacute;n, informaci&oacute;n y dem&aacute;s comunicaciones que <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> env&iacute;e de forma electr&oacute;nica cumplen con los requisitos legales de ser por escrito. Esta condici&oacute;n no afectar&aacute; a los derechos reconocidos por ley al Usuario.</p>
    <p>El Usuario puede enviar notificaciones y/o comunicarse con <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> a trav&eacute;s de los datos de contacto que en estas Condiciones se facilitan y, en su caso, a trav&eacute;s de los espacios de contacto del Sitio Web.</p>
    <p>Igualmente, salvo que se estipule lo contrario, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> puede contactar y/o notificar al Usuario en su correo electr&oacute;nico o en la direcci&oacute;n postal facilitada.</p><strong>
        <h3 style="font-size: 1.7rem;">11. RENUNCIA</h3>
    </strong>
    <p>Ninguna renuncia de <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> a un derecho o acci&oacute;n legal concreta o la falta de requerimiento por <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> del cumplimiento estricto por el Usuario de alguna de sus obligaciones supondr&aacute;, ni una renuncia a otros derechos o acciones derivados de un contrato o de las Condiciones, ni exonerar&aacute; al Usuario del cumplimiento de sus obligaciones.</p>
    <p>Ninguna renuncia de <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> a alguna de las presentes Condiciones o a los derechos o acciones derivados de un contrato surtir&aacute; efecto, a no ser que se establezca expresamente que es una renuncia y se formalice y se le comunique al Usuario por escrito.</p><strong>
        <h3 style="font-size: 1.7rem;">12. NULIDAD</h3>
    </strong>
    <p>Si alguna de las presentes Condiciones fuesen declaradas nulas y sin efecto por resoluci&oacute;n firme dictada por autoridad competente, el resto de las cl&aacute;usulas permanecer&aacute;n en vigor, sin que queden afectadas por dicha declaraci&oacute;n de nulidad.</p><strong>
        <h3 style="font-size: 1.7rem;">13. ACUERDO COMPLETO</h3>
    </strong>
    <p>Las presentes Condiciones y todo documento al que se haga referencia expresa en estas constituyen el acuerdo &iacute;ntegro existente entre el Usuario y <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> en relaci&oacute;n con el objeto de compraventa y sustituyen a cualquier otro pacto, acuerdo o promesa anterior convenida verbalmente o por escrito por las mismas partes.</p>
    <p>El Usuario y <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> reconocen haber consentido la celebraci&oacute;n de un contrato sin haber confiado en ninguna declaraci&oacute;n o promesa hecha por la otra parte, salvo aquello que figura expresamente mencionado en las presentes Condiciones.</p><strong>
        <h3 style="font-size: 1.7rem;">14. PROTECCI&Oacute;N DE DATOS</h3>
    </strong>
    <p>La informaci&oacute;n o datos de car&aacute;cter personal que el Usuario facilite a <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> en el curso de una transacci&oacute;n en el Sitio Web, ser&aacute;n tratados con arreglo a lo establecido en la Pol&iacute;tica de Privacidad o de protecci&oacute;n de datos (contenida, en su caso, en el Aviso Legal y Condiciones Generales de Uso). Al acceder, navegar y/o usar el Sitio Web el Usuario consiente el tratamiento de dicha informaci&oacute;n y datos y declara que toda la informaci&oacute;n o datos que facilita son veraces.</p><strong>
        <h3 style="font-size: 1.7rem;">15. LEGISLACI&Oacute;N APLICABLE Y JURISDICCI&Oacute;N</h3>
    </strong>
    <p>El acceso, navegaci&oacute;n y/o uso de este Sitio Web y los contratos de compra de productos a trav&eacute;s del mismo se regir&aacute;n por la legislaci&oacute;n espa&ntilde;ola.</p>
    <p>Cualquier controversia, problema o desacuerdo que surja o este relacionado con el acceso, navegaci&oacute;n y/o uso del Sitio Web, o con la interpretaci&oacute;n y ejecuci&oacute;n de estas Condiciones, o con los contratos de venta entre <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> y el Usuario, ser&aacute; sometida a la jurisdicci&oacute;n no exclusiva de los juzgados y tribunales espa&ntilde;oles.</p><strong>
        <h3 style="font-size: 1.7rem;">16. QUEJAS Y RECLAMACIONES</h3>
    </strong>
    <p>El Usuario puede hacer llegar a <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> sus quejas, reclamaciones o todo otro comentario que desee realizar a trav&eacute;s de los datos de contacto que se facilitan al principio de estas Condiciones (Informaci&oacute;n General).</p>
    <p>Adem&aacute;s, <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> dispone de hojas oficiales de reclamaci&oacute;n a disposici&oacute;n de los consumidores y usuarios, y que estos pueden solicitar a <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> en cualquier momento, utilizando los datos de contacto que se facilitan al principio de estas Condiciones (Informaci&oacute;n General).</p>
    <p>Asimismo, si de la celebraci&oacute;n de este contrato de compra entre <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> y el Usuario emanara una controversia, el Usuario como consumidor puede solicitar una soluci&oacute;n extrajudicial de controversias, de acuerdo con el Reglamento (UE) 524/2013 del Parlamento Europeo y del Consejo, de 21 de mayo de 2013, sobre resoluci&oacute;n de litigios en l&iacute;nea en materia de consumo y por el que se modifica el Reglamento (CE) 2006/2004 y la Directiva 2009/22/CE. Puede acceder a este m&eacute;todo a trav&eacute;s del siguiente sitio web: https://ec.europa.eu/consumers/odr/.</p>
    <p>Este documento de Condiciones Generales de Venta ha sido creado mediante el generador de <a href="https://textos-legales.edgartamarit.com/" style="color: rgba(var(--bs-body-color-rgb),var(--bs-text-opacity)) !important;">plantilla de condiciones generales de venta</a> online el d&iacute;a 29/11/2023.</p>
</div>
<header style="text-align: center !important;color: rgb(33, 37, 41);font-size: 16px;"><strong>
        <h2 style="font-size: 2rem;">POL&Iacute;TICA DE COOKIES</h2>
    </strong><strong>
        <h4 style="font-size: 1.5rem;"><span style="border-bottom: 1px solid rgb(0, 0, 0);">www.lucecine.com</span></h4>
    </strong></header>
<div style="text-align: start;color: rgb(33, 37, 41);font-size: 16px;">
    <p>El acceso a este Sitio Web puede implicar la utilizaci&oacute;n de cookies. Las cookies son peque&ntilde;as cantidades de informaci&oacute;n que se almacenan en el navegador utilizado por cada Usuario &mdash;en los distintos dispositivos que pueda utilizar para navegar&mdash; para que el servidor recuerde cierta informaci&oacute;n que posteriormente y &uacute;nicamente el servidor que la implement&oacute; leer&aacute;. Las cookies facilitan la navegaci&oacute;n, la hacen m&aacute;s amigable, y no da&ntilde;an el dispositivo de navegaci&oacute;n.</p>
    <p>Las cookies son procedimientos autom&aacute;ticos de recogida de informaci&oacute;n relativa a las preferencias determinadas por el Usuario durante su visita al Sitio Web con el fin de reconocerlo como Usuario, y personalizar su experiencia y el uso del Sitio Web, y pueden tambi&eacute;n, por ejemplo, ayudar a identificar y resolver errores.</p>
    <p>La informaci&oacute;n recabada a trav&eacute;s de las cookies puede incluir la fecha y hora de visitas al Sitio Web, las p&aacute;ginas visionadas, el tiempo que ha estado en el Sitio Web y los sitios visitados justo antes y despu&eacute;s del mismo. Sin embargo, ninguna cookie permite que esta misma pueda contactarse con el n&uacute;mero de tel&eacute;fono del Usuario o con cualquier otro medio de contacto personal. Ninguna cookie puede extraer informaci&oacute;n del disco duro del Usuario o robar informaci&oacute;n personal. La &uacute;nica manera de que la informaci&oacute;n privada del Usuario forme parte del archivo Cookie es que el usuario d&eacute; personalmente esa informaci&oacute;n al servidor.</p>
    <p>Las cookies que permiten identificar a una persona se consideran datos personales. Por tanto, a las mismas les ser&aacute; de aplicaci&oacute;n la Pol&iacute;tica de Privacidad anteriormente descrita. En este sentido, para la utilizaci&oacute;n de las mismas ser&aacute; necesario el consentimiento del Usuario. Este consentimiento ser&aacute; comunicado, en base a una elecci&oacute;n aut&eacute;ntica, ofrecido mediante una decisi&oacute;n afirmativa y positiva, antes del tratamiento inicial, removible y documentado.</p>
    <div><strong>
            <h4 style="font-size: 1.5rem;">Cookies propias</h4>
        </strong>
        <p>Son aquellas cookies que son enviadas al ordenador o dispositivo del Usuario y gestionadas exclusivamente por <span style="border-bottom: 1px solid rgb(0, 0, 0);">Lucecine</span> para el mejor funcionamiento del Sitio Web. La informaci&oacute;n que se recaba se emplea para mejorar la calidad del Sitio Web y su Contenido y su experiencia como Usuario. Estas cookies permiten reconocer al Usuario como visitante recurrente del Sitio Web y adaptar el contenido para ofrecerle contenidos que se ajusten a sus preferencias.</p>
    </div><strong>
        <h4 style="font-size: 1.5rem;">Deshabilitar, rechazar y eliminar cookies</h4>
    </strong>
    <p>El Usuario puede deshabilitar, rechazar y eliminar las cookies &mdash;total o parcialmente&mdash; instaladas en su dispositivo mediante la configuraci&oacute;n de su navegador (entre los que se encuentran, por ejemplo, Chrome, Firefox, Safari, Explorer). En este sentido, los procedimientos para rechazar y eliminar las cookies pueden diferir de un navegador de Internet a otro. En consecuencia, el Usuario debe acudir a las instrucciones facilitadas por el propio navegador de Internet que est&eacute; utilizando. En el supuesto de que rechace el uso de cookies &mdash;total o parcialmente&mdash; podr&aacute; seguir usando el Sitio Web, si bien podr&aacute; tener limitada la utilizaci&oacute;n de algunas de las prestaciones del mismo.</p>
    <p>Este documento de Pol&iacute;tica de Cookies ha sido creado mediante el generador de <a href="https://textos-legales.edgartamarit.com/" style="color: rgba(var(--bs-body-color-rgb),var(--bs-text-opacity)) !important;">plantilla de pol&iacute;tica de cookies web gratis</a> online el d&iacute;a 29/11/2023.</p>
</div>
<div>
<header style="text-align: center !important;color: rgb(33, 37, 41);font-size: 16px;"><strong>
        <h2 style="font-size: 2rem;">LICENCIA CREATIVE COMMONS</h2>
    </strong><strong>
        <h4 style="font-size: 1.5rem;"><span style="border-bottom: 1px solid rgb(0, 0, 0);">www.lucecine.com</span></h4>
    </strong></header>
    <p>This work is licensed under CC BY-NC-ND 4.0. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/</p>
    <p>Attribution-NonCommercial-NoDerivatives 4.0 International
This license requires that reusers give credit to the creator. It allows reusers to copy and distribute the material in any medium or format in unadapted form and for noncommercial purposes only.
<ul>
    <li>BY: Credit must be given to you, the creator.</li>
    <li>NC: Only noncommercial use of your work is permitted.
Noncommercial means not primarily intended for or directed towards commercial advantage or monetary compensation.</li>
    <li>ND: No derivatives or adaptations of your work are permitted.</li>
</ul>
</p>
</div>
<div>
<header style="text-align: center !important;color: rgb(33, 37, 41);font-size: 16px;"><strong>
        <h2 style="font-size: 2rem;">CONTENIDO GENERADO POR IA</h2>
    </strong><strong>
        <h4 style="font-size: 1.5rem;"><span style="border-bottom: 1px solid rgb(0, 0, 0);">www.lucecine.com</span></h4>
    </strong></header>
    <p>Dicho contenido no está sujeto a la normativa sobre la propiedad intelectual. El contenido generado por IA de este sitio web es el siguiente: </p>
    <ul>
        <li>Logotipo de la página</li>
        <li>Imagenes de la página Acerca De</li>
    </ul>
</div>



</div>
        </section>
    </main>
    <?php include("includes/footer.php"); ?>

</body>

</html>